services:
  api:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/company_db
      - INITIALIZE_DB=true  # Set to initialize the database
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
    depends_on:
      - db
    restart: on-failure

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "8080:8080"

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
    ports:
      - "5432:5432"

volumes:
  postgres_data: